import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Wrapper from './shared/Wrapper'
import Footer from './components/Footer'

import Providers from './store/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E-COM-WEBSITE',
  description: 'Generated by create next app',
}

export default function RootLayout({                       
  children,
}: {
  children: React.ReactNode
}) {                                     
  return (
    <html lang="en">
      <body className={inter.className}>
       
       <Wrapper>
<Providers >
<Header />
{children}


<Footer />

</Providers>
      
       </Wrapper>
      

        </body>
    </html>
  )
}
